//
// Created by Elvira Granqvist on 2021-05-17.
//

#ifndef DATASTRUKTURER_OCH_ALGORITMER_BOOST_AUTO_TEST_SUITE_H
#define DATASTRUKTURER_OCH_ALGORITMER_BOOST_AUTO_TEST_SUITE_H

class BOOST_AUTO_TEST_SUITE {};

#endif // DATASTRUKTURER_OCH_ALGORITMER_BOOST_AUTO_TEST_SUITE_H
